-- Schema definitions for vgmcharts
-- Postgres-first, small relational slice for web app development.

BEGIN;

CREATE TYPE release_type_enum AS ENUM ('album', 'single', 'ep', 'compilation');
CREATE TYPE recording_category_enum AS ENUM ('official', 'fan_cover', 'fan_song');
CREATE TYPE artist_role_enum AS ENUM ('primary', 'featured', 'composer', 'producer');

CREATE TABLE franchises (
    franchise_id INTEGER PRIMARY KEY,
    franchise_name TEXT NOT NULL UNIQUE
);

CREATE TABLE artists (
    artist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_name TEXT NOT NULL,
    spotify_artist_id TEXT UNIQUE,
    slug TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT artists_name_not_blank CHECK (btrim(artist_name) <> ''),
    CONSTRAINT artists_spotify_artist_id_not_blank CHECK (spotify_artist_id IS NULL OR btrim(spotify_artist_id) <> ''),
    CONSTRAINT artists_slug_not_blank CHECK (slug IS NULL OR btrim(slug) <> '')
);

CREATE TABLE releases (
    release_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_title TEXT NOT NULL,
    short_description TEXT,
    franchise_id INTEGER NOT NULL REFERENCES franchises (franchise_id),
    release_type release_type_enum NOT NULL,
    release_date DATE,
    total_tracks INTEGER,
    spotify_album_id TEXT UNIQUE,
    upc TEXT UNIQUE,
    ean TEXT UNIQUE,
    jp_catalog_no TEXT UNIQUE,
    label_name TEXT,
    copyright_c TEXT,
    copyright_p TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT releases_total_tracks_positive CHECK (total_tracks IS NULL OR total_tracks > 0),
    CONSTRAINT releases_title_not_blank CHECK (btrim(release_title) <> ''),
    CONSTRAINT releases_upc_not_blank CHECK (upc IS NULL OR btrim(upc) <> ''),
    CONSTRAINT releases_ean_not_blank CHECK (ean IS NULL OR btrim(ean) <> ''),
    CONSTRAINT releases_spotify_album_id_not_blank CHECK (spotify_album_id IS NULL OR btrim(spotify_album_id) <> ''),
    CONSTRAINT releases_jp_catalog_no_not_blank CHECK (jp_catalog_no IS NULL OR btrim(jp_catalog_no) <> ''),
    CONSTRAINT releases_label_name_not_blank CHECK (label_name IS NULL OR btrim(label_name) <> ''),
    CONSTRAINT releases_copyright_c_not_blank CHECK (copyright_c IS NULL OR btrim(copyright_c) <> ''),
    CONSTRAINT releases_copyright_p_not_blank CHECK (copyright_p IS NULL OR btrim(copyright_p) <> '')
);

CREATE TABLE release_artwork (
    release_id INTEGER NOT NULL REFERENCES releases (release_id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    url TEXT NOT NULL,
    width INTEGER,
    height INTEGER,
    PRIMARY KEY (release_id, source),
    CONSTRAINT release_artwork_width_positive CHECK (width IS NULL OR width > 0),
    CONSTRAINT release_artwork_height_positive CHECK (height IS NULL OR height > 0)
);

CREATE TABLE recordings (
    recording_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recording_title TEXT NOT NULL,
    duration_ms INTEGER,
    isrc TEXT UNIQUE,
    franchise_id INTEGER NOT NULL REFERENCES franchises (franchise_id),
    category recording_category_enum NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT recordings_duration_positive CHECK (duration_ms IS NULL OR duration_ms > 0),
    CONSTRAINT recordings_title_not_blank CHECK (btrim(recording_title) <> ''),
    CONSTRAINT recordings_isrc_not_blank CHECK (isrc IS NULL OR btrim(isrc) <> '')
);

CREATE TABLE release_artists (
    release_id INTEGER NOT NULL REFERENCES releases (release_id) ON DELETE CASCADE,
    artist_id INTEGER NOT NULL REFERENCES artists (artist_id) ON DELETE CASCADE,
    artist_role artist_role_enum NOT NULL DEFAULT 'primary',
    artist_order INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (release_id, artist_id, artist_role),
    CONSTRAINT release_artists_artist_order_positive CHECK (artist_order > 0),
    CONSTRAINT release_artists_release_artist_order_unique UNIQUE (release_id, artist_order)
);

CREATE TABLE tracks (
    track_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id INTEGER NOT NULL REFERENCES releases (release_id) ON DELETE CASCADE,
    recording_id INTEGER NOT NULL REFERENCES recordings (recording_id) ON DELETE CASCADE,
    spotify_track_id TEXT UNIQUE,
    disc_number INTEGER NOT NULL DEFAULT 1,
    track_number INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT tracks_disc_positive CHECK (disc_number > 0),
    CONSTRAINT tracks_track_positive CHECK (track_number > 0),
    CONSTRAINT tracks_spotify_track_id_not_blank CHECK (spotify_track_id IS NULL OR btrim(spotify_track_id) <> ''),
    CONSTRAINT tracks_release_disc_track_unique UNIQUE (release_id, disc_number, track_number),
    CONSTRAINT tracks_release_recording_unique UNIQUE (release_id, recording_id)
);

CREATE TABLE tracks_artists (
    track_id INTEGER NOT NULL REFERENCES tracks (track_id) ON DELETE CASCADE,
    artist_id INTEGER NOT NULL REFERENCES artists (artist_id) ON DELETE CASCADE,
    artist_role artist_role_enum NOT NULL DEFAULT 'primary',
    artist_order INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (track_id, artist_id, artist_role),
    CONSTRAINT tracks_artists_artist_order_positive CHECK (artist_order > 0),
    CONSTRAINT tracks_artists_track_artist_order_unique UNIQUE (track_id, artist_order)
);

CREATE TABLE tracks_popularity (
    track_id INTEGER NOT NULL REFERENCES tracks (track_id) ON DELETE CASCADE,
    dt TIMESTAMPTZ NOT NULL,
    spotify_popularity INTEGER NOT NULL,
    PRIMARY KEY (track_id, dt),
    CONSTRAINT tracks_popularity_range CHECK (spotify_popularity BETWEEN 0 AND 100)
);

CREATE INDEX idx_recordings_category ON recordings (category);
CREATE INDEX idx_recordings_isrc ON recordings (isrc);
CREATE INDEX idx_tracks_spotify_track_id ON tracks (spotify_track_id);
CREATE INDEX idx_tracks_release_id ON tracks (release_id);
CREATE INDEX idx_tracks_recording_id ON tracks (recording_id);
CREATE INDEX idx_releases_release_date ON releases (release_date);
CREATE INDEX idx_tracks_popularity_dt ON tracks_popularity (dt DESC);

COMMIT;
