-- Schema definitions for vgmcharts

CREATE TABLE dummy_data (
    id SERIAL PRIMARY KEY,
    value TEXT NOT NULL
);

INSERT INTO dummy_data (value) VALUES
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF'),
    ('ABCDKJHFKJGFKJGFKJSGFKJGFKJF');

GRANT SELECT ON dummy_data TO "2ndmachine";
