#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$POSTGRES_USER2" WITH PASSWORD '$POSTGRES_PASSWORD2';
    GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_USER2";
    GRANT USAGE ON SCHEMA public TO "$POSTGRES_USER2";
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$POSTGRES_USER2";
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$POSTGRES_USER2";
EOSQL
